### ISSUE TITLE
installation

### ISSUE THREAD

**Issue by jalbertbowden** [ndanielsen/dc_traffic_tickets#16]
got through to:  
Check that it is running with:  
docker-compose ps  

throwing an error for missing .env file:  
ERROR: Couldn't find env file: /Users/j.albertbowden/Desktop/github/dc_traffic_tickets/.env  

thoughts?

**Comment by jalbertbowden** [comment]
this is on desktop btw

**Comment by ndanielsen** [comment]
in the command line:

`cp local.env .env`
